#!/usr/bin/env node
// Turns db/catalog/core.json into an idempotent SQL seed for public.foods and
// public.food_portions. Re-running the generated file updates existing catalog
// rows in place (matched on fdc_id) and never touches user-created foods.
//
//   node scripts/build-seed.mjs
//
// The catalog is the source of truth; do not hand-edit supabase/seed/.

import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const SRC = join(root, 'db/catalog/core.json');
const OUT = join(root, 'supabase/seed/0001_foods.sql');

const q = (s) => (s === null || s === undefined || s === '' ? 'null' : `'${String(s).replace(/'/g, "''")}'`);

// numeric(6,2) columns: two decimals, and clamp to the schema's check ranges.
// USDA carbohydrate is "by difference" and lands slightly below zero for a few
// very-low-carb foods; that is arithmetic noise, not a negative carb count.
const warnings = [];
function num(value, { name, column, min = 0, max }) {
  if (value === null || value === undefined) return 'null';
  let v = Number(value);
  if (!Number.isFinite(v)) throw new Error(`${name}: ${column} is not a number (${value})`);
  if (v < min || v > max) {
    warnings.push(`${name}: ${column} ${v} clamped to [${min}, ${max}]`);
    v = Math.min(Math.max(v, min), max);
  }
  return v.toFixed(2);
}

const foods = JSON.parse(readFileSync(SRC, 'utf8'));
if (!Array.isArray(foods) || foods.length === 0) throw new Error('catalog is empty');

const seen = new Set();
const rows = [];
let portionCount = 0;

for (const f of foods) {
  if (!Number.isInteger(f.id)) throw new Error(`bad fdc_id on ${f.name}`);
  if (seen.has(f.id)) throw new Error(`duplicate fdc_id ${f.id} (${f.name})`);
  seen.add(f.id);

  const portions = (f.portions ?? []).map((p) => ({
    amount: Number(p.amount),
    unit: String(p.unit),
    grams: Number(Number(p.grams).toFixed(2)),
  }));
  portionCount += portions.length;

  rows.push(
    '  (' +
      [
        f.id,
        q(f.name),
        q(f.cat ?? null),
        num(f.kcal, { name: f.name, column: 'kcal', max: 900 }),
        num(f.protein, { name: f.name, column: 'protein_g', max: 100 }),
        num(f.fat, { name: f.name, column: 'fat_g', max: 100 }),
        num(f.carbs, { name: f.name, column: 'carbs_g', max: 100 }),
        num(f.fiber, { name: f.name, column: 'fiber_g', max: 100 }),
        num(f.sodium, { name: f.name, column: 'sodium_mg', max: 100000 }),
        `${q(JSON.stringify(portions))}::jsonb`,
      ].join(', ') +
      ')'
  );
}

const sql = `-- GENERATED by scripts/build-seed.mjs from db/catalog/core.json — do not edit.
-- ${rows.length} foods, ${portionCount} portions. Safe to re-run: catalog rows are
-- matched on fdc_id and updated in place, user-created foods are never touched.
--
-- Run as the service role (Supabase SQL editor, or \\i from psql). The anon and
-- authenticated roles have no write access to catalog rows by design.

begin;

create temporary table _seed_foods (
  fdc_id    integer primary key,
  name      text not null,
  category  text,
  kcal      numeric(6,2) not null,
  protein_g numeric(6,2),
  fat_g     numeric(6,2),
  carbs_g   numeric(6,2),
  fiber_g   numeric(6,2),
  sodium_mg numeric(8,2),
  portions  jsonb not null
) on commit drop;

insert into _seed_foods
  (fdc_id, name, category, kcal, protein_g, fat_g, carbs_g, fiber_g, sodium_mg, portions)
values
${rows.join(',\n')};

insert into public.foods
  (fdc_id, name, category, kcal, protein_g, fat_g, carbs_g, fiber_g, sodium_mg)
select fdc_id, name, category, kcal, protein_g, fat_g, carbs_g, fiber_g, sodium_mg
from _seed_foods
on conflict (fdc_id) do update set
  name      = excluded.name,
  category  = excluded.category,
  kcal      = excluded.kcal,
  protein_g = excluded.protein_g,
  fat_g     = excluded.fat_g,
  carbs_g   = excluded.carbs_g,
  fiber_g   = excluded.fiber_g,
  sodium_mg = excluded.sodium_mg;

-- Portions are replaced wholesale rather than merged: they have no stable id in
-- the source data, so a diff would be guesswork. Only catalog foods are cleared.
delete from public.food_portions p
using public.foods f
where p.food_id = f.id and f.fdc_id is not null;

insert into public.food_portions (food_id, amount, unit, grams)
select f.id, x.amount, x.unit, x.grams
from _seed_foods s
join public.foods f on f.fdc_id = s.fdc_id
cross join lateral jsonb_to_recordset(s.portions)
  as x(amount numeric, unit text, grams numeric);

commit;

-- Keep the planner honest about the freshly loaded catalog.
analyze public.foods;
analyze public.food_portions;
`;

mkdirSync(dirname(OUT), { recursive: true });
writeFileSync(OUT, sql);

for (const w of warnings) console.warn(`warn: ${w}`);
console.log(`wrote ${OUT}: ${rows.length} foods, ${portionCount} portions`);
